# Generated by Django 4.1.4 on 2022-12-11 06:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('repoapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='projects',
            table='Projects',
        ),
    ]
