# Generated by Django 4.1.4 on 2022-12-11 14:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('repoapp', '0003_remove_projects_updated_at'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Projects',
            new_name='Project',
        ),
    ]
