# Generated by Django 4.1.4 on 2022-12-11 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repoapp', '0004_rename_projects_project'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
