# Generated by Django 4.1.4 on 2022-12-12 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repoapp', '0005_alter_project_deleted_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.GenericIPAddressField()),
            ],
            options={
                'db_table': 'ip_visitors',
            },
        ),
    ]
